action_selector: epsilon_greedy
agent:
  entity_scheme: true
  imagine: false
  recurrent: false
  subtask_cond: mask
agent_output_type: q
alloc_embed_dim: 128
alloc_n_heads: 4
alloc_q_weight_decay: 0
alloc_target_update_interval: 50
attn_embed_dim: 128
attn_n_heads: 4
batch_size: 32
batch_size_run: 8
buffer_cpu_only: false
buffer_opt_mem: true
buffer_size: 5000
checkpoint_run_name: ''
checkpoint_unique_id: ''
double_q: true
entity_last_action: true
env: ff
env_args:
  end_on_any_burn: false
  entity_scheme: true
  episode_limit: 150
  game_config:
    base_build_rate: 0.125
    fire_burn_rate: 0.035
    fire_growth_rate: 1.1
    fire_reduce_rate: 0.25
    generalist_help_factor: 0.45
    init_fire_chance: 0.4
  reward_scale: 20
epsilon_anneal_time: 2000000
epsilon_finish: 0.05
epsilon_start: 1.0
eval_all_models: false
eval_all_scen: false
eval_n_task_range: ''
eval_path: null
eval_sep: false
evaluate: false
fps: 2
gamma: 0.99
grad_norm_clip: 10
hier_agent:
  action_length: 5
  alloc_critic: standard
  alloc_eps: 1.0-0.0-0.05
  alloc_opt: rmsprop
  alloc_policy: autoreg
  copa: false
  copa_vi_loss: true
  decay_old: 150000
  entropy_loss: 0.01
  mask_copa: true
  max_bs: 400
  n_proposals: 32
  pi_ag_attn: false
  pi_autoreg: true
  pi_pointer_net: true
  prop_alloc_eps: 1.0-0.05-0.2
  sel_task_upd: true
  subtask_mask: true
  task_allocation: aql
hypernet_embed: 128
learner: q_learner
learner_log_interval: 10000
lmbda: 0.5
load_step: 0
log_interval: 10000
lr: 0.0005
mac: entity_mac
mask_subtask_actions: false
max_traj_len: 64
mixer: flex_qmix
mixer_subtask_cond: null
mixing_embed_dim: 32
multi_task: true
n_extra_tasks: 0
n_extra_units: 0
name: qmix_atten
obs_agent_id: true
obs_last_action: true
optim_alpha: 0.99
optim_eps: 1.0e-05
pi_checkpoint_run_name: ''
popart: true
rnn_hidden_dim: 64
runner: parallel
runner_log_interval: 10000
save_model: true
save_model_interval: 1000000
save_replay: false
scenario: single_scen
softmax_mixing_weights: true
t_max: 15000000
target_update_interval: 200
tb_dirname: tb_logs
test_greedy: true
test_interval: 50000
test_nepisode: 160
training_iters: 8
use_cuda: false
use_tensorboard: true
use_wandb: false
vi_lambda: 5.0e-05
video_path: null
wb_entity: entity
wb_notes: []
wb_tags: []
weight_decay: 0
